changed maintenance script again

diff --git a/sys-maintenance b/sys-maintenance
--- a/sys-maintenance
+++ b/sys-maintenance
@@ -1,9 +1,6 @@
 #!/bin/bash
 SECONDS=0
 
-LOGFILE="/var/log/sys-maintenance.log"
-touch "$LOGFILE" || { echo "Cannot write to $LOGFILE"; exit 1; }
-
 command -v fd >/dev/null || { echo "fd not found"; exit 1; }
 command -v paccache >/dev/null || { echo "paccache not found"; exit 1; }
 
@@ -11,6 +8,9 @@ if [[ "$EUID" -ne 0 ]]; then
   echo "This script must be run as root" | tee -a "$LOGFILE"
   exit 1
 fi
+
+LOGFILE="/var/log/sys-maintenance.log"
+touch "$LOGFILE" || { echo "Cannot write to $LOGFILE"; exit 1; }
 
 echo "==========================================" | tee -a "$LOGFILE"
 echo " " | tee -a "$LOGFILE"
